#!/bin/bash
# Setup script for Google OAuth

echo "========================================="
echo "Google OAuth Setup Helper"
echo "========================================="

# Check if environment variables are set
if [ -z "$GOOGLE_CLIENT_ID" ] || [ -z "$GOOGLE_CLIENT_SECRET" ]; then
    echo "❌ Google OAuth credentials not set."
    echo ""
    echo "To set them, run:"
    echo "export GOOGLE_CLIENT_ID='your-client-id-here'"
    echo "export GOOGLE_CLIENT_SECRET='your-client-secret-here'"
    echo "export OAUTHLIB_INSECURE_TRANSPORT='true'"
    echo ""
    echo "Or create a .env file with:"
    echo "GOOGLE_CLIENT_ID=your-client-id-here"
    echo "GOOGLE_CLIENT_SECRET=your-client-secret-here"
    echo "OAUTHLIB_INSECURE_TRANSPORT=true"
    echo ""
    echo "Then run: source .env"
else
    echo "✅ Google OAuth credentials are set."
    echo "   Client ID: ${GOOGLE_CLIENT_ID:0:20}..."
    echo "   Client Secret: ${GOOGLE_CLIENT_SECRET:0:20}..."
fi

echo ""
echo "========================================="
echo "Application Configuration"
echo "========================================="
echo "✅ Application is configured for port 5000"
echo "✅ Google OAuth redirect URI:"
echo "   http://127.0.0.1:5000/login/google/authorized"
echo "   http://localhost:5000/login/google/authorized"
echo ""
echo "Make sure your Google Cloud Console has these exact redirect URIs."
echo ""
echo "========================================="
echo "To start the application:"
echo "========================================="
echo "1. Set environment variables (if not already set)"
echo "2. Activate virtual environment:"
echo "   source venv/bin/activate"
echo "3. Start the application:"
echo "   python app.py"
echo "4. Open browser to:"
echo "   http://localhost:5000"
echo ""
echo "========================================="